import { hostname } from 'os';


const env = require('dotenv');
env.config({
  path: process.env.NODE_ENV === 'production' ? '.env' : '.env.local',
});

const {
  NODE_ENV,
  APP_PORT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_NAME,
  JWT_SECRET,
  MONGO_DB_USERNAME,
  MONGO_DB_PASSWORD,
  MONGO_DB_NAME,
  MONGO_DB,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_BUCKET_NAME,
  AWS_SDK_LOAD_CONFIG,
} = process.env;

export const envConfig = {
  ENV: NODE_ENV,
  HOSTNAME: hostname(),
  APP_PORT: parseFloat(APP_PORT),
  DB_HOST: DB_HOST,
  DB_PORT: DB_PORT,
  DB_USER: DB_USER,
  DB_PASSWORD: DB_PASSWORD,
  DB_NAME: DB_NAME,
  JWT_SECRET_KEY: JWT_SECRET,
  MONGO_DB_USERNAME: MONGO_DB_USERNAME,
  MONGO_DB_PASSWORD: MONGO_DB_PASSWORD,
  MONGO_DB_NAME: MONGO_DB_NAME,
  MONGO_DB: MONGO_DB,
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY,
  AWS_REGION: AWS_REGION,
  AWS_BUCKET_NAME: AWS_BUCKET_NAME,
  AWS_SDK_LOAD_CONFIG: AWS_SDK_LOAD_CONFIG,
};
